export const products = [
  {
    id: 1,
    name: "Assassin's Creed Mirage",
    description: "Infiltración y sigilo en Bagdad.",
    price: 59.99,
    category: "Acción",
    genre: "Sigilo",
    console: "Multiplataforma",
    multiplayer: false,
    release: 2023,
    image: "/img/assassins_creed_mirage.jpg"
  },
  {
    id: 2,
    name: "Assassin's Creed Valhalla",
    description: "Explora los reinos nórdicos como Eivor.",
    price: 59.99,
    category: "RPG",
    genre: "Mundo abierto",
    console: "Multiplataforma",
    multiplayer: false,
    release: 2020,
    image: "/img/assassins_creed_valhalla.jpg"
  },
  {
    id: 3,
    name: "Assassin's Creed Shadows",
    description: "La saga llega al Japón feudal.",
    price: 69.99,
    category: "Acción",
    genre: "Aventura",
    console: "Multiplataforma",
    multiplayer: true,
    release: 2024,
    image: "/img/assassins_creed_shadows.jpeg"
  },
  {
    id: 4,
    name: "Star Wars Jedi: Survivor",
    description: "Secuela de Fallen Order con más exploración.",
    price: 69.99,
    category: "Aventura",
    genre: "Acción",
    console: "Multiplataforma",
    multiplayer: false,
    release: 2023,
    image: "/img/star_wars_jedi_survivor.jpg"
  },
  {
    id: 5,
    name: "Hogwarts Legacy",
    description: "Vive tu propia historia en el mundo mágico.",
    price: 69.99,
    category: "RPG",
    genre: "Mundo abierto",
    console: "Multiplataforma",
    multiplayer: false,
    release: 2023,
    image: "/img/hogwarts_legacy.jpg"
  },
  {
    id: 6,
    name: "The Legend of Zelda: Tears of the Kingdom",
    description: "Explora las islas flotantes de Hyrule.",
    price: 69.99,
    category: "Aventura",
    genre: "Exploración",
    console: "Nintendo Switch",
    multiplayer: false,
    release: 2023,
    image: "/img/zelda_totk.jpg"
  },
  {
    id: 7,
    name: "Sekiro: Shadows Die Twice",
    description: "Desafío y precisión en Japón feudal.",
    price: 59.99,
    category: "Acción",
    genre: "Soulslike",
    console: "Multiplataforma",
    multiplayer: false,
    release: 2019,
    image: "/img/sekiro.jpg"
  },
  {
    id: 8,
    name: "Nier Automata",
    description: "Combate y filosofía en un futuro distópico.",
    price: 39.99,
    category: "RPG",
    genre: "Hack and Slash",
    console: "Multiplataforma",
    multiplayer: false,
    release: 2017,
    image: "/img/nier_automata.jpg"
  },
  {
    id: 9,
    name: "Stray",
    description: "Explora una ciudad futurista como un gato perdido.",
    price: 29.99,
    category: "Aventura",
    genre: "Puzzle",
    console: "PlayStation / PC",
    multiplayer: false,
    release: 2022,
    image: "/img/stray.jpg"
  },
  {
    id: 10,
    name: "Spider-Man: Miles Morales",
    description: "Nueva York con poderes arácnidos.",
    price: 49.99,
    category: "Acción",
    genre: "Superhéroes",
    console: "PlayStation",
    multiplayer: false,
    release: 2020,
    image: "/img/spiderman_miles.jpg"
  },
  {
    id: 11,
    name: "Black Myth: Wukong",
    description: "Una visión épica del Rey Mono.",
    price: 69.99,
    category: "Acción",
    genre: "Mitología china",
    console: "PC / Consolas",
    multiplayer: false,
    release: 2024,
    image: "/img/black_myth.jpg"
  }
];
